import Mathlib.Data.Fintype.Card
import Mathlib.Data.Finite.Card
import Schematic.Math.Relation.ReflTransGen

/-!
Finite hypermaps for the direct four-colour theorem development.

The Robertson--Sanders--Seymour--Thomas proof, and Gonthier's mechanically
checked proof of it, use finite hypermaps as the planar-combinatorial core.
This file starts the reusable Lean interface: a hypermap is a finite type of
darts equipped with three permutations, traditionally called `edge`, `node`,
and `face`, whose composite is the identity.
-/

namespace Schematic.Math.GraphTheory

universe u v

namespace FourColor

/-- One step along the cyclic orbit generated by a permutation, allowing both
directions. -/
inductive PermLink {α : Type u} (σ : Equiv.Perm α) : α → α → Prop
  | forward (x : α) : PermLink σ x (σ x)
  | backward (x : α) : PermLink σ x (σ.symm x)

namespace PermLink

variable {α : Type u} (σ : Equiv.Perm α)

theorem symm {x y : α}
    (hxy : PermLink σ x y) :
    PermLink σ y x := by
  cases hxy with
  | forward =>
      simpa using (PermLink.backward (σ := σ) (σ x))
  | backward =>
      simpa using (PermLink.forward (σ := σ) (σ.symm x))

end PermLink

/-- Membership in the orbit generated by a permutation. -/
def PermReachable {α : Type u} (σ : Equiv.Perm α) (x y : α) : Prop :=
  Relation.ReflTransGen (PermLink σ) x y

namespace PermReachable

variable {α : Type u} (σ : Equiv.Perm α)

theorem refl (x : α) :
    PermReachable σ x x :=
  Relation.ReflTransGen.refl

theorem forward (x : α) :
    PermReachable σ x (σ x) :=
  Relation.ReflTransGen.single (PermLink.forward x)

theorem backward (x : α) :
    PermReachable σ x (σ.symm x) :=
  Relation.ReflTransGen.single (PermLink.backward x)

theorem symm {x y : α}
    (hxy : PermReachable σ x y) :
    PermReachable σ y x :=
  Relation.ReflTransGen.symmetric (fun _ _ => PermLink.symm σ) hxy

theorem trans {x y z : α}
    (hxy : PermReachable σ x y)
    (hyz : PermReachable σ y z) :
    PermReachable σ x z :=
  Relation.ReflTransGen.trans hxy hyz

/-- A pointwise simulation of forward permutation steps transports complete
orbit reachability.  Backward steps need no separate hypothesis: they are the
reverse of the simulated forward step at the inverse source. -/
theorem map_of_forward_simulation
    {β : Type v} (τ : Equiv.Perm β) (code : α → β)
    (hstep : ∀ x : α, PermReachable τ (code x) (code (σ x)))
    {x y : α} (hxy : PermReachable σ x y) :
    PermReachable τ (code x) (code y) :=
  hxy.lift' code fun x _ hlink => by
    cases hlink with
    | forward => exact hstep x
    | backward =>
        simpa using PermReachable.symm τ (hstep (σ.symm x))

end PermReachable

/-- Every point of a finite permutation has a positive forward period.  This is
the small finite-cycle pigeonhole fact needed to replace Coq's explicit
shortened face paths. -/
theorem perm_exists_pos_iterate_eq_self
    {α : Type u} [Fintype α] (σ : Equiv.Perm α) (x : α) :
    ∃ n : ℕ, 0 < n ∧ (σ : α → α)^[n] x = x := by
  classical
  let N := Fintype.card α
  let f : Fin (N + 1) → α := fun i => (σ : α → α)^[i.val] x
  have hnotinj : ¬ Function.Injective f := by
    intro hinj
    have hle : Fintype.card (Fin (N + 1)) ≤ Fintype.card α :=
      Fintype.card_le_of_injective f hinj
    simp [N] at hle
  rw [Function.Injective] at hnotinj
  push Not at hnotinj
  rcases hnotinj with ⟨i, j, hij, hne⟩
  have hvalne : i.val ≠ j.val := by
    intro hv
    apply hne
    exact Fin.ext hv
  have hlt_or : i.val < j.val ∨ j.val < i.val :=
    Nat.lt_or_gt_of_ne hvalne
  have step_lt : ∀ {i j : Fin (N + 1)}, f i = f j → i.val < j.val →
      ∃ n : ℕ, 0 < n ∧ (σ : α → α)^[n] x = x := by
    intro i j hij hlt
    rcases Nat.exists_eq_add_of_lt hlt with ⟨d, hd⟩
    refine ⟨d + 1, Nat.succ_pos d, ?_⟩
    have hiter0 : (σ : α → α)^[i.val] x =
        (σ : α → α)^[j.val] x := hij
    have hiter : (σ : α → α)^[i.val] x =
        (σ : α → α)^[i.val] ((σ : α → α)^[d + 1] x) := by
      calc
        (σ : α → α)^[i.val] x = (σ : α → α)^[j.val] x := hiter0
        _ = (σ : α → α)^[i.val + d + 1] x := by rw [hd]
        _ = (σ : α → α)^[i.val + (d + 1)] x := by
          rw [Nat.add_assoc]
        _ = (σ : α → α)^[i.val] ((σ : α → α)^[d + 1] x) := by
          rw [Function.iterate_add_apply]
    have hinj_iter : Function.Injective ((σ : α → α)^[i.val]) :=
      σ.injective.iterate i.val
    have hx : x = (σ : α → α)^[d + 1] x := hinj_iter hiter
    exact hx.symm
  rcases hlt_or with hlt | hgt
  · exact step_lt hij hlt
  · exact step_lt hij.symm hgt

/-- In a finite permutation orbit, the inverse step is some number of forward
steps. -/
theorem perm_exists_iterate_eq_symm_apply
    {α : Type u} [Fintype α] (σ : Equiv.Perm α) (x : α) :
    ∃ n : ℕ, (σ : α → α)^[n] x = σ.symm x := by
  rcases perm_exists_pos_iterate_eq_self σ (σ.symm x) with ⟨n, hnpos, hn⟩
  rcases Nat.exists_eq_add_of_lt hnpos with ⟨d, hd⟩
  refine ⟨d, ?_⟩
  rw [hd] at hn
  simpa [Function.iterate_succ_apply] using hn

theorem permReachable_of_iterate_eq
    {α : Type u} (σ : Equiv.Perm α) {x y : α} {n : ℕ}
    (h : (σ : α → α)^[n] x = y) :
    PermReachable σ x y := by
  induction n generalizing x with
  | zero =>
      rw [← h]
      exact PermReachable.refl σ x
  | succ n ih =>
      have htail : (σ : α → α)^[n] (σ x) = y := by
        rw [Function.iterate_succ_apply] at h
        exact h
      exact PermReachable.trans σ (PermReachable.forward σ x)
        (ih (x := σ x) htail)

/-- Finite permutation reachability can be represented by a forward iterate.
This packages the finite-cycle part of later face-band arguments. -/
theorem permReachable_exists_iterate
    {α : Type u} [Fintype α] (σ : Equiv.Perm α) {x y : α}
    (hxy : PermReachable σ x y) :
    ∃ n : ℕ, (σ : α → α)^[n] x = y := by
  induction hxy with
  | refl => exact ⟨0, rfl⟩
  | @tail b c hxb hbc ih =>
      rcases ih with ⟨n, hn⟩
      cases hbc with
      | forward =>
          refine ⟨n.succ, ?_⟩
          simp [Function.iterate_succ_apply', hn]
      | backward =>
          rcases perm_exists_iterate_eq_symm_apply σ b with ⟨m, hm⟩
          refine ⟨m + n, ?_⟩
          calc
            (σ : α → α)^[m + n] x =
                (σ : α → α)^[m] ((σ : α → α)^[n] x) := by
              rw [Function.iterate_add_apply]
            _ = (σ : α → α)^[m] b := by rw [hn]
            _ = σ.symm b := hm

theorem permReachable_iff_exists_iterate
    {α : Type u} [Fintype α] (σ : Equiv.Perm α) {x y : α} :
    PermReachable σ x y ↔ ∃ n : ℕ, (σ : α → α)^[n] x = y := by
  constructor
  · exact permReachable_exists_iterate σ
  · rintro ⟨n, hn⟩
    exact permReachable_of_iterate_eq σ hn

theorem permReachable_refl_iff_eq
    {α : Type u} {x y : α} :
    PermReachable (Equiv.refl α) x y ↔ x = y := by
  constructor
  · intro h
    exact h.apply_eq id (fun {_ _} hlink => by cases hlink <;> rfl)
  · intro h
    subst h
    exact PermReachable.refl (Equiv.refl α) x

/-- Choose the first forward iterate witnessing finite permutation reachability. -/
theorem permReachable_exists_first_iterate
    {α : Type u} [Fintype α] [DecidableEq α]
    (σ : Equiv.Perm α) {x y : α}
    (hxy : PermReachable σ x y) :
    ∃ n : ℕ,
      (σ : α → α)^[n] x = y ∧
        ∀ k : ℕ, k < n → (σ : α → α)^[k] x ≠ y := by
  classical
  let h := permReachable_exists_iterate σ hxy
  refine ⟨Nat.find h, Nat.find_spec h, ?_⟩
  intro k hk
  exact Nat.find_min h hk

theorem permReachable_exists_first_positive_iterate
    {α : Type u} [Fintype α] [DecidableEq α]
    (σ : Equiv.Perm α) {x y : α}
    (hxy : PermReachable σ x y)
    (hxy_ne : x ≠ y) :
    ∃ n : ℕ,
      0 < n ∧
        (σ : α → α)^[n] x = y ∧
          ∀ k : ℕ, k < n → (σ : α → α)^[k] x ≠ y := by
  rcases permReachable_exists_first_iterate σ hxy with ⟨n, hn, hmin⟩
  refine ⟨n, ?_, hn, hmin⟩
  by_contra hnzero
  apply hxy_ne
  have hz : n = 0 := Nat.eq_zero_of_not_pos hnzero
  simpa [hz] using hn

theorem permLink_symmPerm_iff
    {α : Type u} (σ : Equiv.Perm α) {x y : α} :
    PermLink σ.symm x y ↔ PermLink σ x y := by
  constructor
  · intro hxy
    cases hxy with
    | forward => exact PermLink.backward (σ := σ) x
    | backward =>
        simpa using (PermLink.forward (σ := σ) x)
  · intro hxy
    cases hxy with
    | forward =>
        simpa using (PermLink.backward (σ := σ.symm) x)
    | backward =>
        exact PermLink.forward (σ := σ.symm) x

theorem perm_conj_symm_apply
    {α : Type u} {β : Type v}
    (e : α ≃ β)
    (σ : Equiv.Perm α)
    (τ : Equiv.Perm β)
    (h : ∀ x : α, e (σ x) = τ (e x))
    (x : α) :
    e (σ.symm x) = τ.symm (e x) := by
  apply τ.injective
  calc
    τ (e (σ.symm x)) = e (σ (σ.symm x)) := (h (σ.symm x)).symm
    _ = e x := by simp
    _ = τ (τ.symm (e x)) := by simp

theorem perm_conj_symm_equiv
    {α : Type u} {β : Type v}
    (e : α ≃ β)
    (σ : Equiv.Perm α)
    (τ : Equiv.Perm β)
    (h : ∀ x : α, e (σ x) = τ (e x))
    (y : β) :
    e.symm (τ y) = σ (e.symm y) := by
  apply e.injective
  simp [h]

theorem permLink_conj
    {α : Type u} {β : Type v}
    (e : α ≃ β)
    (σ : Equiv.Perm α)
    (τ : Equiv.Perm β)
    (h : ∀ x : α, e (σ x) = τ (e x))
    {x y : α}
    (hxy : PermLink σ x y) :
    PermLink τ (e x) (e y) := by
  cases hxy with
  | forward =>
      simpa [h x] using PermLink.forward (σ := τ) (e x)
  | backward =>
      simpa [perm_conj_symm_apply e σ τ h x] using
        PermLink.backward (σ := τ) (e x)

theorem permReachable_conj
    {α : Type u} {β : Type v}
    (e : α ≃ β)
    (σ : Equiv.Perm α)
    (τ : Equiv.Perm β)
    (h : ∀ x : α, e (σ x) = τ (e x))
    {x y : α}
    (hxy : PermReachable σ x y) :
    PermReachable τ (e x) (e y) :=
  hxy.lift' e fun _ _ hlink =>
    Relation.ReflTransGen.single (permLink_conj e σ τ h hlink)

theorem permReachable_conj_iff
    {α : Type u} {β : Type v}
    (e : α ≃ β)
    (σ : Equiv.Perm α)
    (τ : Equiv.Perm β)
    (h : ∀ x : α, e (σ x) = τ (e x))
    {x y : α} :
    PermReachable σ x y ↔ PermReachable τ (e x) (e y) := by
  constructor
  · exact permReachable_conj e σ τ h
  · intro hxy
    have h' : ∀ z : β, e.symm (τ z) = σ (e.symm z) :=
      perm_conj_symm_equiv e σ τ h
    have hback :=
      permReachable_conj e.symm τ σ h' hxy
    simpa using hback

theorem permReachable_symmPerm_iff
    {α : Type u} (σ : Equiv.Perm α) {x y : α} :
    PermReachable σ.symm x y ↔ PermReachable σ x y := by
  constructor
  · intro hxy
    exact hxy.lift' id fun _ _ hlink =>
      Relation.ReflTransGen.single ((permLink_symmPerm_iff σ).mp hlink)
  · intro hxy
    exact hxy.lift' id fun _ _ hlink =>
      Relation.ReflTransGen.single ((permLink_symmPerm_iff σ).mpr hlink)

/-- The setoid of cyclic orbits of a permutation. -/
def permOrbitSetoid {α : Type u} (σ : Equiv.Perm α) : Setoid α where
  r := PermReachable σ
  iseqv := {
    refl := PermReachable.refl σ
    symm := by
      intro _ _ hxy
      exact PermReachable.symm σ hxy
    trans := by
      intro _ _ _ hxy hyz
      exact PermReachable.trans σ hxy hyz }

/-- Cyclic orbit quotient of a permutation. -/
def PermOrbit {α : Type u} (σ : Equiv.Perm α) : Type u :=
  Quotient (permOrbitSetoid σ)

/-- Cyclic-orbit quotients are invariant under a conjugating equivalence of
permutations. -/
noncomputable def permOrbitEquivOfConj
    {α : Type u} {β : Type v}
    (e : α ≃ β) (σ : Equiv.Perm α) (τ : Equiv.Perm β)
    (h : forall x : α, e (σ x) = τ (e x)) :
    PermOrbit σ ≃ PermOrbit τ :=
  Quotient.congr e (by
    intro x y
    exact permReachable_conj_iff e σ τ h)

noncomputable def permOrbitReflEquiv (α : Type u) :
    PermOrbit (Equiv.refl α) ≃ α where
  toFun := Quotient.lift id (by
    intro _ _ h
    exact permReachable_refl_iff_eq.mp h)
  invFun := fun x => Quotient.mk (permOrbitSetoid (Equiv.refl α)) x
  left_inv := by
    intro q
    refine Quotient.inductionOn q ?_
    intro _x
    rfl
  right_inv := by
    intro _x
    rfl

namespace PermOrbit

variable {α : Type u} (σ : Equiv.Perm α)

noncomputable instance fintype [Fintype α] : Fintype (PermOrbit σ) := by
  classical
  letI : DecidableRel (permOrbitSetoid σ).r := Classical.decRel _
  exact Quotient.fintype (permOrbitSetoid σ)

/-- The cyclic orbit containing an element. -/
def of (x : α) : PermOrbit σ :=
  Quotient.mk (permOrbitSetoid σ) x

theorem of_eq_of {x y : α}
    (hxy : PermReachable σ x y) :
    of σ x = of σ y :=
  Quot.sound hxy

theorem of_apply (x : α) :
    of σ (σ x) = of σ x :=
  of_eq_of σ (PermReachable.symm σ (PermReachable.forward σ x))

theorem of_symm_apply (x : α) :
    of σ (σ.symm x) = of σ x :=
  of_eq_of σ (PermReachable.symm σ (PermReachable.backward σ x))

/-- Inverting a permutation does not change its cyclic orbits. -/
noncomputable def equivSymm :
    PermOrbit σ.symm ≃ PermOrbit σ :=
  Quotient.congr (Equiv.refl α) (by
    intro x y
    exact permReachable_symmPerm_iff σ)

end PermOrbit

theorem permOrbitCount_symm
    {α : Type u} (σ : Equiv.Perm α) :
    Nat.card (PermOrbit σ.symm) = Nat.card (PermOrbit σ) :=
  Nat.card_congr (PermOrbit.equivSymm σ)

/-- A finite hypermap, presented by the three mutually inverse permutations
`edge`, `node`, and `face`. -/
structure Hypermap where
  Dart : Type u
  [fintypeDart : Fintype Dart]
  [decidableEqDart : DecidableEq Dart]
  edge : Equiv.Perm Dart
  node : Equiv.Perm Dart
  face : Equiv.Perm Dart
  node_face_edge : ∀ x : Dart, node (face (edge x)) = x

attribute [instance] Hypermap.fintypeDart Hypermap.decidableEqDart

namespace Hypermap

variable (G : Hypermap.{u})

/-- Build a finite hypermap from the single cyclic cancellation law used by
MathComp's `Hypermap` constructor.  On a finite dart type, cancellation makes
each of the three endofunctions bijective. -/
noncomputable def ofCancel3
    {α : Type u} [Fintype α] [DecidableEq α]
    (edge node face : α → α)
    (cancel3 : ∀ x : α, node (face (edge x)) = x) : Hypermap.{u} := by
  have hedgeInj : Function.Injective edge := by
    intro x y hxy
    calc
      x = node (face (edge x)) := (cancel3 x).symm
      _ = node (face (edge y)) := by rw [hxy]
      _ = y := cancel3 y
  have hedgeSurj : Function.Surjective edge :=
    Finite.injective_iff_surjective.mp hedgeInj
  have hnodeSurj : Function.Surjective node := by
    intro x
    exact ⟨face (edge x), cancel3 x⟩
  have hnodeInj : Function.Injective node :=
    Finite.injective_iff_surjective.mpr hnodeSurj
  have hfaceInj : Function.Injective face := by
    intro x y hxy
    obtain ⟨a, rfl⟩ := hedgeSurj x
    obtain ⟨b, rfl⟩ := hedgeSurj y
    have hab : a = b := by
      calc
        a = node (face (edge a)) := (cancel3 a).symm
        _ = node (face (edge b)) := by rw [hxy]
        _ = b := cancel3 b
    exact congrArg edge hab
  let edgeEquiv : Equiv.Perm α :=
    Equiv.ofBijective edge
      (Finite.injective_iff_bijective.mp hedgeInj)
  let nodeEquiv : Equiv.Perm α :=
    Equiv.ofBijective node
      (Finite.injective_iff_bijective.mp hnodeInj)
  let faceEquiv : Equiv.Perm α :=
    Equiv.ofBijective face
      (Finite.injective_iff_bijective.mp hfaceInj)
  exact {
    Dart := α
    edge := edgeEquiv
    node := nodeEquiv
    face := faceEquiv
    node_face_edge := cancel3
  }

@[simp]
theorem ofCancel3_edge_apply
    {α : Type u} [Fintype α] [DecidableEq α]
    (edge node face : α → α)
    (cancel3 : ∀ x : α, node (face (edge x)) = x) (x : α) :
    (ofCancel3 edge node face cancel3).edge x = edge x :=
  rfl

@[simp]
theorem ofCancel3_node_apply
    {α : Type u} [Fintype α] [DecidableEq α]
    (edge node face : α → α)
    (cancel3 : ∀ x : α, node (face (edge x)) = x) (x : α) :
    (ofCancel3 edge node face cancel3).node x = node x :=
  rfl

@[simp]
theorem ofCancel3_face_apply
    {α : Type u} [Fintype α] [DecidableEq α]
    (edge node face : α → α)
    (cancel3 : ∀ x : α, node (face (edge x)) = x) (x : α) :
    (ofCancel3 edge node face cancel3).face x = face x :=
  rfl

@[simp]
theorem node_face_edge_apply (x : G.Dart) :
    G.node (G.face (G.edge x)) = x :=
  G.node_face_edge x

/-- Cyclic cancellation in the `edge, node, face` presentation. -/
@[simp]
theorem edge_node_face (x : G.Dart) :
    G.edge (G.node (G.face x)) = x := by
  have h : G.node (G.face x) = G.edge.symm x := by
    simpa using G.node_face_edge (G.edge.symm x)
  calc
    G.edge (G.node (G.face x)) = G.edge (G.edge.symm x) := by rw [h]
    _ = x := by simp

/-- Cyclic cancellation in the `edge, node, face` presentation. -/
@[simp]
theorem face_edge_node (x : G.Dart) :
    G.face (G.edge (G.node x)) = x := by
  have h : G.edge (G.node x) = G.face.symm x := by
    simpa using G.edge_node_face (G.face.symm x)
  calc
    G.face (G.edge (G.node x)) = G.face (G.face.symm x) := by rw [h]
    _ = x := by simp

/-- Cyclically rotate the hypermap permutations:
`edge -> node -> face -> edge`. -/
def permNode : Hypermap where
  Dart := G.Dart
  edge := G.node
  node := G.face
  face := G.edge
  node_face_edge := by
    intro x
    exact G.face_edge_node x

/-- Cyclically rotate the hypermap permutations:
`edge -> face -> node -> edge`. -/
def permFace : Hypermap where
  Dart := G.Dart
  edge := G.face
  node := G.edge
  face := G.node
  node_face_edge := by
    intro x
    exact G.edge_node_face x

/-- Dual hypermap: invert all three permutations and interchange node/face. -/
def dual : Hypermap where
  Dart := G.Dart
  edge := G.edge.symm
  node := G.face.symm
  face := G.node.symm
  node_face_edge := by
    intro x
    have h : G.node (G.face x) = G.edge.symm x := by
      simpa using G.node_face_edge (G.edge.symm x)
    calc
      G.face.symm (G.node.symm (G.edge.symm x)) =
          G.face.symm (G.face x) := by rw [← h]; simp
      _ = x := by simp

/-- Mirror hypermap, matching Gonthier's `mirror`: the edge permutation is
`face ∘ node`, while node and face are inverted. -/
def mirror : Hypermap where
  Dart := G.Dart
  edge := G.node.trans G.face
  node := G.node.symm
  face := G.face.symm
  node_face_edge := by
    intro x
    simp [Equiv.trans_apply]

/-- One directed dart link generated by one of the three hypermap
permutations. -/
def Link (x y : G.Dart) : Prop :=
  y = G.edge x ∨ y = G.node x ∨ y = G.face x

/-- Membership in the dart component generated by all edge, node, and face
links. -/
def Reachable (x y : G.Dart) : Prop :=
  Relation.ReflTransGen G.Link x y

/-- A hypermap is preconnected when all darts lie in the same generated dart
component.  The separate nonemptiness condition is bundled in `Connected`. -/
def Preconnected : Prop :=
  ∀ x y : G.Dart, G.Reachable x y

/-- Connected finite hypermaps are nonempty and have one generated dart
component. -/
def Connected : Prop :=
  Nonempty G.Dart ∧ G.Preconnected

theorem Connected.nonempty
    (hG : G.Connected) :
    Nonempty G.Dart :=
  hG.1

theorem Connected.preconnected
    (hG : G.Connected) :
    G.Preconnected :=
  hG.2

theorem Connected.reachable
    (hG : G.Connected)
    (x y : G.Dart) :
    G.Reachable x y :=
  hG.2 x y

theorem connected_of_preconnected
    [Nonempty G.Dart]
    (hG : G.Preconnected) :
    G.Connected :=
  ⟨inferInstance, hG⟩

theorem reachable_refl (x : G.Dart) :
    G.Reachable x x :=
  Relation.ReflTransGen.refl

theorem reachable_edge (x : G.Dart) :
    G.Reachable x (G.edge x) :=
  Relation.ReflTransGen.single (Or.inl rfl)

theorem reachable_node (x : G.Dart) :
    G.Reachable x (G.node x) :=
  Relation.ReflTransGen.single (Or.inr (Or.inl rfl))

theorem reachable_face (x : G.Dart) :
    G.Reachable x (G.face x) :=
  Relation.ReflTransGen.single (Or.inr (Or.inr rfl))

theorem permNode_link_iff {x y : G.Dart} :
    G.permNode.Link x y ↔ G.Link x y := by
  change
    (y = G.node x ∨ y = G.face x ∨ y = G.edge x) ↔
      (y = G.edge x ∨ y = G.node x ∨ y = G.face x)
  constructor
  · intro hxy
    rcases hxy with hxy | hxy | hxy
    · exact Or.inr (Or.inl hxy)
    · exact Or.inr (Or.inr hxy)
    · exact Or.inl hxy
  · intro hxy
    rcases hxy with hxy | hxy | hxy
    · exact Or.inr (Or.inr hxy)
    · exact Or.inl hxy
    · exact Or.inr (Or.inl hxy)

theorem permFace_link_iff {x y : G.Dart} :
    G.permFace.Link x y ↔ G.Link x y := by
  change
    (y = G.face x ∨ y = G.edge x ∨ y = G.node x) ↔
      (y = G.edge x ∨ y = G.node x ∨ y = G.face x)
  constructor
  · intro hxy
    rcases hxy with hxy | hxy | hxy
    · exact Or.inr (Or.inr hxy)
    · exact Or.inl hxy
    · exact Or.inr (Or.inl hxy)
  · intro hxy
    rcases hxy with hxy | hxy | hxy
    · exact Or.inr (Or.inl hxy)
    · exact Or.inr (Or.inr hxy)
    · exact Or.inl hxy

theorem permNode_reachable {x y : G.Dart}
    (hxy : G.permNode.Reachable x y) :
    G.Reachable x y :=
  hxy.mono fun _ _ h => G.permNode_link_iff.mp h

theorem reachable_permNode {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.permNode.Reachable x y :=
  hxy.mono fun _ _ h => G.permNode_link_iff.mpr h

theorem permFace_reachable {x y : G.Dart}
    (hxy : G.permFace.Reachable x y) :
    G.Reachable x y :=
  hxy.mono fun _ _ h => G.permFace_link_iff.mp h

theorem reachable_permFace {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.permFace.Reachable x y :=
  hxy.mono fun _ _ h => G.permFace_link_iff.mpr h

theorem permNode_preconnected_iff :
    G.permNode.Preconnected ↔ G.Preconnected := by
  constructor
  · intro h x y
    exact G.permNode_reachable (h x y)
  · intro h x y
    exact G.reachable_permNode (h x y)

theorem permFace_preconnected_iff :
    G.permFace.Preconnected ↔ G.Preconnected := by
  constructor
  · intro h x y
    exact G.permFace_reachable (h x y)
  · intro h x y
    exact G.reachable_permFace (h x y)

theorem reachable_edge_symm (x : G.Dart) :
    G.Reachable (G.edge x) x :=
  (G.reachable_face (G.edge x)).trans
    ((G.reachable_node (G.face (G.edge x))).trans
      (by simpa using (G.reachable_refl x)))

theorem reachable_node_symm (x : G.Dart) :
    G.Reachable (G.node x) x :=
  (G.reachable_edge (G.node x)).trans
    ((G.reachable_face (G.edge (G.node x))).trans
      (by simpa using (G.reachable_refl x)))

theorem reachable_face_symm (x : G.Dart) :
    G.Reachable (G.face x) x :=
  (G.reachable_node (G.face x)).trans
    ((G.reachable_edge (G.node (G.face x))).trans
      (by simpa using (G.reachable_refl x)))

theorem edgePermReachable_reachable {x y : G.Dart}
    (hxy : PermReachable G.edge x y) :
    G.Reachable x y :=
  hxy.lift' id fun _ _ h => by
    cases h with
    | forward => exact G.reachable_edge _
    | backward => simpa using G.reachable_edge_symm (G.edge.symm _)

theorem nodePermReachable_reachable {x y : G.Dart}
    (hxy : PermReachable G.node x y) :
    G.Reachable x y :=
  hxy.lift' id fun _ _ h => by
    cases h with
    | forward => exact G.reachable_node _
    | backward => simpa using G.reachable_node_symm (G.node.symm _)

theorem facePermReachable_reachable {x y : G.Dart}
    (hxy : PermReachable G.face x y) :
    G.Reachable x y :=
  hxy.lift' id fun _ _ h => by
    cases h with
    | forward => exact G.reachable_face _
    | backward => simpa using G.reachable_face_symm (G.face.symm _)

theorem dual_link_reachable {x y : G.Dart}
    (hxy : G.dual.Link x y) :
    G.Reachable x y := by
  rcases hxy with hxy | hxy | hxy
  · simpa [dual, hxy] using G.reachable_edge_symm (G.edge.symm x)
  · simpa [dual, hxy] using G.reachable_face_symm (G.face.symm x)
  · simpa [dual, hxy] using G.reachable_node_symm (G.node.symm x)

theorem dual_reachable {x y : G.Dart}
    (hxy : G.dual.Reachable x y) :
    G.Reachable x y :=
  hxy.lift' id fun _ _ h => G.dual_link_reachable h

theorem link_reachable_dual {x y : G.Dart}
    (hxy : G.Link x y) :
    G.dual.Reachable x y := by
  rcases hxy with hxy | hxy | hxy
  · subst y
    convert G.dual.reachable_edge_symm (G.edge x) using 1
    exact (G.edge.symm_apply_apply x).symm
  · subst y
    convert G.dual.reachable_face_symm (G.node x) using 1
    exact (G.node.symm_apply_apply x).symm
  · subst y
    convert G.dual.reachable_node_symm (G.face x) using 1
    exact (G.face.symm_apply_apply x).symm

theorem reachable_dual {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.dual.Reachable x y :=
  hxy.lift' id fun _ _ h => G.link_reachable_dual h

theorem dual_preconnected_iff :
    G.dual.Preconnected ↔ G.Preconnected := by
  constructor
  · intro h x y
    exact G.dual_reachable (h x y)
  · intro h x y
    exact G.reachable_dual (h x y)

theorem mirror_edge_original (x : G.Dart) :
    G.face.symm (G.node.symm x) = G.edge x := by
  have h : G.face (G.edge x) = G.node.symm x := by
    calc
      G.face (G.edge x) =
          G.node.symm (G.node (G.face (G.edge x))) := by
            exact (G.node.symm_apply_apply (G.face (G.edge x))).symm
      _ = G.node.symm x := by rw [G.node_face_edge]
  calc
    G.face.symm (G.node.symm x) = G.face.symm (G.face (G.edge x)) := by
      rw [h]
    _ = G.edge x := by simp

theorem mirror_mirror :
    G.mirror.mirror = G := by
  cases G with
  | mk Dart edge node face node_face_edge =>
      simp [mirror]
      apply Equiv.ext
      intro x
      change face.symm (node.symm x) = edge x
      have h : face (edge x) = node.symm x := by
        calc
          face (edge x) = node.symm (node (face (edge x))) := by
            exact (node.symm_apply_apply (face (edge x))).symm
          _ = node.symm x := by rw [node_face_edge]
      calc
        face.symm (node.symm x) = face.symm (face (edge x)) := by
          rw [← h]
        _ = edge x := by simp

theorem edge_node_eq_face_symm (x : G.Dart) :
    G.edge (G.node x) = G.face.symm x := by
  calc
    G.edge (G.node x) =
        G.face.symm (G.face (G.edge (G.node x))) := by
          exact (G.face.symm_apply_apply (G.edge (G.node x))).symm
    _ = G.face.symm x := by rw [G.face_edge_node]

theorem mirror_edge_conj (x : G.Dart) :
    G.face.symm (G.mirror.edge x) = G.edge.symm (G.face.symm x) := by
  calc
    G.face.symm (G.mirror.edge x) = G.node x := by
      change G.face.symm (G.face (G.node x)) = G.node x
      simp
    _ = G.edge.symm (G.face.symm x) := by
      simpa using congrArg G.edge.symm (G.edge_node_eq_face_symm x)

theorem mirror_link_reachable {x y : G.Dart}
    (hxy : G.mirror.Link x y) :
    G.Reachable x y := by
  rcases hxy with hxy | hxy | hxy
  · subst y
    simpa [mirror, Equiv.trans_apply] using
      (G.reachable_node x).trans (G.reachable_face (G.node x))
  · subst y
    simpa [mirror] using G.reachable_node_symm (G.node.symm x)
  · subst y
    simpa [mirror] using G.reachable_face_symm (G.face.symm x)

theorem mirror_reachable {x y : G.Dart}
    (hxy : G.mirror.Reachable x y) :
    G.Reachable x y :=
  hxy.lift' id fun _ _ h => G.mirror_link_reachable h

theorem link_reachable_mirror {x y : G.Dart}
    (hxy : G.Link x y) :
    G.mirror.Reachable x y := by
  rcases hxy with hxy | hxy | hxy
  · subst y
    have hnode : G.mirror.Reachable x (G.node.symm x) := by
      simpa [mirror] using G.mirror.reachable_node x
    have hface : G.mirror.Reachable (G.node.symm x) (G.edge x) := by
      convert G.mirror.reachable_face (G.node.symm x) using 1
      exact (G.mirror_edge_original x).symm
    exact hnode.trans hface
  · subst y
    convert G.mirror.reachable_node_symm (G.node x) using 1
    exact (G.node.symm_apply_apply x).symm
  · subst y
    convert G.mirror.reachable_face_symm (G.face x) using 1
    exact (G.face.symm_apply_apply x).symm

theorem reachable_mirror {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.mirror.Reachable x y :=
  hxy.lift' id fun _ _ h => G.link_reachable_mirror h

theorem mirror_preconnected_iff :
    G.mirror.Preconnected ↔ G.Preconnected := by
  constructor
  · intro h x y
    exact G.mirror_reachable (h x y)
  · intro h x y
    exact G.reachable_mirror (h x y)

theorem permNode_connected_iff :
    G.permNode.Connected ↔ G.Connected := by
  constructor
  · intro h
    exact ⟨by simpa [permNode] using h.1,
      (G.permNode_preconnected_iff).mp h.2⟩
  · intro h
    exact ⟨by simpa [permNode] using h.1,
      (G.permNode_preconnected_iff).mpr h.2⟩

theorem permFace_connected_iff :
    G.permFace.Connected ↔ G.Connected := by
  constructor
  · intro h
    exact ⟨by simpa [permFace] using h.1,
      (G.permFace_preconnected_iff).mp h.2⟩
  · intro h
    exact ⟨by simpa [permFace] using h.1,
      (G.permFace_preconnected_iff).mpr h.2⟩

theorem dual_connected_iff :
    G.dual.Connected ↔ G.Connected := by
  constructor
  · intro h
    exact ⟨by simpa [dual] using h.1,
      (G.dual_preconnected_iff).mp h.2⟩
  · intro h
    exact ⟨by simpa [dual] using h.1,
      (G.dual_preconnected_iff).mpr h.2⟩

theorem mirror_connected_iff :
    G.mirror.Connected ↔ G.Connected := by
  constructor
  · intro h
    exact ⟨by simpa [mirror] using h.1,
      (G.mirror_preconnected_iff).mp h.2⟩
  · intro h
    exact ⟨by simpa [mirror] using h.1,
      (G.mirror_preconnected_iff).mpr h.2⟩

theorem reachable_of_link_symm {x y : G.Dart}
    (hxy : G.Link x y) :
    G.Reachable y x := by
  rcases hxy with hxy | hxy | hxy
  · simpa [hxy] using G.reachable_edge_symm x
  · simpa [hxy] using G.reachable_node_symm x
  · simpa [hxy] using G.reachable_face_symm x

theorem reachable_symm {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.Reachable y x :=
  Relation.ReflTransGen.symm_of_step
    (fun {_ _} h => G.reachable_of_link_symm h) hxy

theorem reachable_trans {x y z : G.Dart}
    (hxy : G.Reachable x y)
    (hyz : G.Reachable y z) :
    G.Reachable x z :=
  hxy.trans hyz

/-- The dart-component equivalence relation generated by the three hypermap
permutations. -/
def reachableSetoid : Setoid G.Dart where
  r := G.Reachable
  iseqv := {
    refl := G.reachable_refl
    symm := by
      intro _ _ hxy
      exact G.reachable_symm hxy
    trans := by
      intro _ _ _ hxy hyz
      exact G.reachable_trans hxy hyz }

/-- A generated dart component. -/
def Component : Type u :=
  Quot G.reachableSetoid

/-- The cyclic rotation `permNode` has the same generated dart components. -/
noncomputable def componentEquivPermNode :
    G.permNode.Component ≃ G.Component :=
  Quotient.congr (Equiv.refl G.Dart) (by
    intro x y
    exact ⟨fun hxy => G.permNode_reachable hxy,
      fun hxy => G.reachable_permNode hxy⟩)

/-- The cyclic rotation `permFace` has the same generated dart components. -/
noncomputable def componentEquivPermFace :
    G.permFace.Component ≃ G.Component :=
  Quotient.congr (Equiv.refl G.Dart) (by
    intro x y
    exact ⟨fun hxy => G.permFace_reachable hxy,
      fun hxy => G.reachable_permFace hxy⟩)

/-- The dual hypermap has the same generated dart components. -/
noncomputable def componentEquivDual :
    G.dual.Component ≃ G.Component :=
  Quotient.congr (Equiv.refl G.Dart) (by
    intro x y
    exact ⟨fun hxy => G.dual_reachable hxy,
      fun hxy => G.reachable_dual hxy⟩)

/-- The mirror hypermap has the same generated dart components. -/
noncomputable def componentEquivMirror :
    G.mirror.Component ≃ G.Component :=
  Quotient.congr (Equiv.refl G.Dart) (by
    intro x y
    exact ⟨fun hxy => G.mirror_reachable hxy,
      fun hxy => G.reachable_mirror hxy⟩)

/-- The generated dart component containing a dart. -/
def componentOf (x : G.Dart) : G.Component :=
  Quot.mk G.reachableSetoid x

/-- Cyclic edge orbits of a hypermap. -/
abbrev EdgeOrbit : Type u :=
  PermOrbit G.edge

/-- Cyclic node orbits of a hypermap. -/
abbrev NodeOrbit : Type u :=
  PermOrbit G.node

/-- Cyclic face orbits of a hypermap. -/
abbrev FaceOrbit : Type u :=
  PermOrbit G.face

/-- Edge cycles of the mirror correspond to edge cycles of the original
hypermap. -/
noncomputable def mirrorEdgeOrbitEquiv :
    G.mirror.EdgeOrbit ≃ G.EdgeOrbit :=
  (Quotient.congr G.face.symm (by
      intro x y
      change PermReachable G.mirror.edge x y ↔
        PermReachable G.edge.symm (G.face.symm x) (G.face.symm y)
      exact permReachable_conj_iff G.face.symm G.mirror.edge G.edge.symm
        (fun z => G.mirror_edge_conj z))).trans
    (PermOrbit.equivSymm G.edge)

/-- Number of generated dart components. -/
noncomputable def componentCount : Nat :=
  Nat.card G.Component

/-- Number of edge cycles. -/
noncomputable def edgeOrbitCount : Nat :=
  Nat.card G.EdgeOrbit

/-- Number of node cycles. -/
noncomputable def nodeOrbitCount : Nat :=
  Nat.card G.NodeOrbit

/-- Number of face cycles. -/
noncomputable def faceOrbitCount : Nat :=
  Nat.card G.FaceOrbit

/-- The left-hand side of Gonthier's hypermap Euler expression:
`2 * components + darts`. -/
noncomputable def eulerLeft : Nat :=
  2 * G.componentCount + Fintype.card G.Dart

/-- The right-hand side of Gonthier's hypermap Euler expression:
edge cycles plus node cycles plus face cycles. -/
noncomputable def eulerRight : Nat :=
  G.edgeOrbitCount + G.nodeOrbitCount + G.faceOrbitCount

/-- Hypermap genus as the truncated half-difference used in the computational
proof.  The missing nontruncation assertion is the usual `even_genus` theorem. -/
noncomputable def genus : Nat :=
  (G.eulerLeft - G.eulerRight) / 2

/-- The nontruncation assertion for the hypermap genus formula. -/
noncomputable def EvenGenus : Prop :=
  G.eulerLeft = 2 * G.genus + G.eulerRight

/-- Euler-planarity for hypermaps, matching the genus-zero condition in the
checked four-colour proof. -/
noncomputable def EulerPlanar : Prop :=
  G.genus = 0

theorem eulerPlanar_of_isEmpty
    (G : Hypermap.{u}) [IsEmpty G.Dart] :
    G.EulerPlanar := by
  classical
  haveI : IsEmpty G.Component :=
    ⟨fun c => Quotient.inductionOn c (fun x => isEmptyElim x)⟩
  haveI : IsEmpty G.EdgeOrbit :=
    ⟨fun c => Quotient.inductionOn c (fun x => isEmptyElim x)⟩
  haveI : IsEmpty G.NodeOrbit :=
    ⟨fun c => Quotient.inductionOn c (fun x => isEmptyElim x)⟩
  haveI : IsEmpty G.FaceOrbit :=
    ⟨fun c => Quotient.inductionOn c (fun x => isEmptyElim x)⟩
  simp [EulerPlanar, genus, eulerLeft, eulerRight, componentCount,
    edgeOrbitCount, nodeOrbitCount, faceOrbitCount]

theorem permNode_eulerRight :
    G.permNode.eulerRight = G.eulerRight := by
  change
    G.nodeOrbitCount + G.faceOrbitCount + G.edgeOrbitCount =
      G.edgeOrbitCount + G.nodeOrbitCount + G.faceOrbitCount
  ac_rfl

theorem permFace_eulerRight :
    G.permFace.eulerRight = G.eulerRight := by
  change
    G.faceOrbitCount + G.edgeOrbitCount + G.nodeOrbitCount =
      G.edgeOrbitCount + G.nodeOrbitCount + G.faceOrbitCount
  ac_rfl

theorem dual_eulerRight :
    G.dual.eulerRight = G.eulerRight := by
  change
    Nat.card (PermOrbit G.edge.symm) +
        Nat.card (PermOrbit G.face.symm) +
      Nat.card (PermOrbit G.node.symm) =
        G.edgeOrbitCount + G.nodeOrbitCount + G.faceOrbitCount
  rw [permOrbitCount_symm G.edge, permOrbitCount_symm G.face,
    permOrbitCount_symm G.node]
  ac_rfl

theorem mirror_edgeOrbitCount :
    G.mirror.edgeOrbitCount = G.edgeOrbitCount :=
  Nat.card_congr G.mirrorEdgeOrbitEquiv

theorem mirror_eulerRight :
    G.mirror.eulerRight = G.eulerRight := by
  change
    G.mirror.edgeOrbitCount +
        Nat.card (PermOrbit G.node.symm) +
      Nat.card (PermOrbit G.face.symm) =
        G.edgeOrbitCount + G.nodeOrbitCount + G.faceOrbitCount
  rw [G.mirror_edgeOrbitCount, permOrbitCount_symm G.node,
    permOrbitCount_symm G.face]
  rfl

theorem permNode_componentCount :
    G.permNode.componentCount = G.componentCount :=
  Nat.card_congr G.componentEquivPermNode

theorem permFace_componentCount :
    G.permFace.componentCount = G.componentCount :=
  Nat.card_congr G.componentEquivPermFace

theorem dual_componentCount :
    G.dual.componentCount = G.componentCount :=
  Nat.card_congr G.componentEquivDual

theorem mirror_componentCount :
    G.mirror.componentCount = G.componentCount :=
  Nat.card_congr G.componentEquivMirror

theorem permNode_eulerLeft :
    G.permNode.eulerLeft = G.eulerLeft := by
  change
    2 * G.permNode.componentCount + Fintype.card G.Dart =
      2 * G.componentCount + Fintype.card G.Dart
  rw [G.permNode_componentCount]

theorem permFace_eulerLeft :
    G.permFace.eulerLeft = G.eulerLeft := by
  change
    2 * G.permFace.componentCount + Fintype.card G.Dart =
      2 * G.componentCount + Fintype.card G.Dart
  rw [G.permFace_componentCount]

theorem dual_eulerLeft :
    G.dual.eulerLeft = G.eulerLeft := by
  change
    2 * G.dual.componentCount + Fintype.card G.Dart =
      2 * G.componentCount + Fintype.card G.Dart
  rw [G.dual_componentCount]

theorem mirror_eulerLeft :
    G.mirror.eulerLeft = G.eulerLeft := by
  change
    2 * G.mirror.componentCount + Fintype.card G.Dart =
      2 * G.componentCount + Fintype.card G.Dart
  rw [G.mirror_componentCount]

theorem permNode_genus :
    G.permNode.genus = G.genus := by
  simp [genus, G.permNode_eulerLeft, G.permNode_eulerRight]

theorem permFace_genus :
    G.permFace.genus = G.genus := by
  simp [genus, G.permFace_eulerLeft, G.permFace_eulerRight]

theorem dual_genus :
    G.dual.genus = G.genus := by
  simp [genus, G.dual_eulerLeft, G.dual_eulerRight]

theorem mirror_genus :
    G.mirror.genus = G.genus := by
  simp [genus, G.mirror_eulerLeft, G.mirror_eulerRight]

theorem permNode_evenGenus_iff :
    G.permNode.EvenGenus ↔ G.EvenGenus := by
  simp [EvenGenus, G.permNode_eulerLeft, G.permNode_eulerRight,
    G.permNode_genus]

theorem permFace_evenGenus_iff :
    G.permFace.EvenGenus ↔ G.EvenGenus := by
  simp [EvenGenus, G.permFace_eulerLeft, G.permFace_eulerRight,
    G.permFace_genus]

theorem dual_evenGenus_iff :
    G.dual.EvenGenus ↔ G.EvenGenus := by
  simp [EvenGenus, G.dual_eulerLeft, G.dual_eulerRight, G.dual_genus]

theorem mirror_evenGenus_iff :
    G.mirror.EvenGenus ↔ G.EvenGenus := by
  simp [EvenGenus, G.mirror_eulerLeft, G.mirror_eulerRight, G.mirror_genus]

theorem permNode_eulerPlanar_iff :
    G.permNode.EulerPlanar ↔ G.EulerPlanar := by
  simp [EulerPlanar, G.permNode_genus]

theorem permFace_eulerPlanar_iff :
    G.permFace.EulerPlanar ↔ G.EulerPlanar := by
  simp [EulerPlanar, G.permFace_genus]

theorem dual_eulerPlanar_iff :
    G.dual.EulerPlanar ↔ G.EulerPlanar := by
  simp [EulerPlanar, G.dual_genus]

theorem mirror_eulerPlanar_iff :
    G.mirror.EulerPlanar ↔ G.EulerPlanar := by
  simp [EulerPlanar, G.mirror_genus]

theorem componentOf_eq_componentOf {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.componentOf x = G.componentOf y :=
  Quot.sound hxy

theorem reachable_of_componentOf_eq {x y : G.Dart}
    (hxy : G.componentOf x = G.componentOf y) :
    G.Reachable x y :=
  Quotient.exact hxy

theorem componentOf_eq_iff {x y : G.Dart} :
    G.componentOf x = G.componentOf y ↔ G.Reachable x y := by
  constructor
  · exact G.reachable_of_componentOf_eq
  · exact G.componentOf_eq_componentOf

theorem Connected.componentOf_eq
    (hG : G.Connected)
    (x y : G.Dart) :
    G.componentOf x = G.componentOf y :=
  G.componentOf_eq_componentOf (Connected.reachable (G := G) hG x y)

theorem componentOf_edge (x : G.Dart) :
    G.componentOf (G.edge x) = G.componentOf x :=
  G.componentOf_eq_componentOf (G.reachable_edge_symm x)

theorem componentOf_node (x : G.Dart) :
    G.componentOf (G.node x) = G.componentOf x :=
  G.componentOf_eq_componentOf (G.reachable_node_symm x)

theorem componentOf_face (x : G.Dart) :
    G.componentOf (G.face x) = G.componentOf x :=
  G.componentOf_eq_componentOf (G.reachable_face_symm x)

end Hypermap

end FourColor

end Schematic.Math.GraphTheory
