import Schematic.Math.GraphTheory.Minors.Society.SplitRouting.Foundations.TailTransport.CleanTailExtraction
import Schematic.Math.GraphTheory.Minors.Society.SplitRouting.Foundations.TailTransport.EndpointBoundary
import Schematic.Math.GraphTheory.Minors.Society.SplitRouting.Foundations.TailTransport.SideSeparation
