import Mathlib.Dynamics.PeriodicPts.Lemmas
import Mathlib.Logic.Embedding.Set
import Schematic.Math.GraphTheory.Embedding.Iso
import Schematic.Math.GraphTheory.Embedding.Geometry.List
import Schematic.Math.GraphTheory.Embedding.Geometry.Path

/-!
Basic hypermap geometry predicates.

This starts the port of Gonthier's `geometry.v`: bridge/loop freeness and the
plain/cubic/precubic structural predicates used by the minimal-counterexample
and cube-reduction layers.
-/

namespace Schematic.Math.GraphTheory

namespace FourColor

namespace Hypermap

variable (G : Hypermap)

/-- No face orbit contains both ends of an edge link. -/
def Bridgeless : Prop :=
  ∀ x : G.Dart, Not (PermReachable G.face x (G.edge x))

/-- No node orbit contains both ends of an edge link. -/
def Loopless : Prop :=
  ∀ x : G.Dart, Not (PermReachable G.node x (G.edge x))

/-- All edge orbits have the two-dart shape. -/
def Plain : Prop :=
  ∀ x : G.Dart, G.edge (G.edge x) = x ∧ G.edge x ≠ x

/-- All node orbits have the three-dart shape. -/
def Cubic : Prop :=
  ∀ x : G.Dart, G.node (G.node (G.node x)) = x ∧ G.node x ≠ x

/-- The node orbits meeting `A` have the three-dart shape.  This is the
Prop-valued counterpart of Coq's `cubicb A`. -/
def CubicOn (A : G.Dart → Prop) : Prop :=
  ∀ x : G.Dart, A x →
    G.node (G.node (G.node x)) = x ∧ G.node x ≠ x

/-- All node orbits away from the listed perimeter darts are cubic.  This is
Coq's `quasicubic r`; configuration maps satisfy this weaker property rather
than global cubicity. -/
def Quasicubic (r : List G.Dart) : Prop :=
  G.CubicOn (fun x => x ∉ r)

/-- The source geometry used by Coq's quiz embedding theorem. -/
structure PlainQuasicubic (r : List G.Dart) : Prop where
  plain : G.Plain
  quasicubic : G.Quasicubic r

/-- Every node orbit has size at most three, expressed as a period bound. -/
def Precubic : Prop :=
  ∀ x : G.Dart,
    G.node x = x ∨ G.node (G.node x) = x ∨
      G.node (G.node (G.node x)) = x

/-- Every face orbit has at least five distinct first iterates. -/
def Pentagonal : Prop :=
  ∀ x : G.Dart,
    x ≠ G.face x ∧
      x ≠ G.face (G.face x) ∧
        x ≠ G.face (G.face (G.face x)) ∧
          x ≠ G.face (G.face (G.face (G.face x)))

/-- Face-adjacency of two ring darts, through an `rlink` from some dart in the
first face.  This is Coq's `adj`: `rlink z y` is face-reachability from
`edge z` to `y`. -/
def RingAdj (x y : G.Dart) : Prop :=
  ∃ z : G.Dart, PermReachable G.face x z ∧
    PermReachable G.face (G.edge z) y

/-- Coq `geometry.v::adjE`. -/
theorem RingAdj.edge_self (x : G.Dart) :
    G.RingAdj x (G.edge x) :=
  ⟨x, PermReachable.refl G.face x,
    PermReachable.refl G.face (G.edge x)⟩

/-- Coq `geometry.v::adjN`. -/
theorem RingAdj.node_self (x : G.Dart) :
    G.RingAdj (G.node x) x := by
  refine ⟨G.node x, PermReachable.refl G.face (G.node x), ?_⟩
  rw [Hypermap.edge_node_eq_face_symm]
  simpa using PermReachable.forward G.face (G.face.symm x)

/-- Coq `chordless r`: a face adjacency between two listed boundary darts can
only join cyclic neighbours.  The membership proof in
`List.prev`/`List.next` fixes the same first-occurrence convention as
MathComp's list operations; all uses have a duplicate-free ring. -/
def Chordless (r : List G.Dart) : Prop :=
  ∀ x : G.Dart, ∀ hx : x ∈ r, ∀ y : G.Dart, y ∈ r →
    G.RingAdj x y →
      y = r.prev x hx ∨ y = r.next x hx

/-- The face band generated by a finite list of darts.  This is the Prop-valued
counterpart of Coq's `fband`: a dart lies in the band when it is in the face
orbit of one of the listed sources. -/
def FaceBand (r : List G.Dart) (u : G.Dart) : Prop :=
  ∃ x : G.Dart, x ∈ r ∧ PermReachable G.face x u

/-- Coq `clink`: one contour step, either a reverse-node step or a face step.
This is deliberately narrower than `Hypermap.Link`, which also includes edge
and forward-node steps. -/
def CLink (x y : G.Dart) : Prop :=
  y = G.node.symm x ∨ y = G.face x

/-- Coq `path clink x p`: a contour path following reverse-node or face
links. -/
def CPath (x : G.Dart) : List G.Dart → Prop
  := List.RelPath G.CLink x

/-- Coq `connect clink`: reachability by C-links. -/
def CConnect (x y : G.Dart) : Prop :=
  Relation.ReflTransGen G.CLink x y

/-- Coq `mem2 p a b`: `a` occurs at or before `b` in the list.  We use a
propositional decomposition because the Jordan layer only needs the ordering
and membership content of MathComp's boolean predicate. -/
def ListMemBeforeEq {α : Type _} (xs : List α) (a b : α) : Prop :=
  ∃ pre rest : List α, xs = pre ++ a :: rest ∧ b ∈ a :: rest

/-- Coq `Moebius_path`: a nontrivial duplicate-free C-path with the crossing
node condition from `hypermap.v`. -/
def MoebiusPath : List G.Dart → Prop
  | [] => False
  | x :: p =>
      (x :: p).Nodup ∧
        G.CPath x p ∧
          ListMemBeforeEq p
            (G.node.symm ((x :: p).getLastD x)) (G.node x)

/-- Coq `Jordan`: no Moebius path exists. -/
def Jordan : Prop :=
  ∀ q : List G.Dart, ¬ G.MoebiusPath q

/-- Coq `dlink r x y`: a component link from a dart not on the ring.  The
Lean relation uses the local `Hypermap.CLink`, matching Coq `clink`. -/
def DLink (r : List G.Dart) (x y : G.Dart) : Prop :=
  x ∉ r ∧ G.CLink x y

/-- Coq `path (dlink r) x p`: an explicit disk-component path. -/
def DPath (r : List G.Dart) (x : G.Dart) : List G.Dart → Prop
  := List.RelPath (G.DLink r) x

/-- Coq `dconnect r x y`: an internally ring-disjoint component path from the
reverse node predecessor of `y` to `x`. -/
def DConnect (r : List G.Dart) (x y : G.Dart) : Prop :=
  Relation.ReflTransGen (G.DLink r) (G.node.symm y) x

/-- The local step `rclink` used in Coq `snip.v`: follow the face of a dart,
except that darts on the ring first cross their edge. -/
def RCLStep (r : List G.Dart) (x : G.Dart) : G.Dart :=
  G.face (if x ∈ r then G.edge x else x)

/-- Coq `fpath rclink x p` for the local `rclink` step used inside
`diskE_edge`. -/
def RCLPath (r : List G.Dart) (x : G.Dart) : List G.Dart → Prop
  := List.RelPath (fun a b => G.RCLStep r a = b) x

/-- Coq `fcycle rclink`: a nonempty `rclink` path whose final dart steps back
to the start. -/
def RCLCycle (r : List G.Dart) : List G.Dart → Prop
  | [] => False
  | x :: p => G.RCLPath r x p ∧ G.RCLStep r ((x :: p).getLastD x) = x

/-- Coq `diskN r`: the node-closed disk generated by the ring. -/
def DiskN (r : List G.Dart) (x : G.Dart) : Prop :=
  ∃ y : G.Dart, y ∈ r ∧ G.DConnect r x y

/-- Coq `diskE r`: the edge-interior of the disk, i.e. `diskN r` without the
ring darts. -/
def DiskE (r : List G.Dart) (x : G.Dart) : Prop :=
  G.DiskN r x ∧ x ∉ r

/-- Coq `diskF r`: the face-interior of the disk, i.e. `diskN r` without the
face band of the ring. -/
def DiskF (r : List G.Dart) (x : G.Dart) : Prop :=
  G.DiskN r x ∧ ¬ G.FaceBand r x

/-- Coq `diskFC r`: the strict outside of the face-closure of the disk. -/
def DiskFC (r : List G.Dart) (x : G.Dart) : Prop :=
  ¬ G.DiskN r x ∧ ¬ G.FaceBand r x

theorem dConnect_refl_node_symm
    (r : List G.Dart) (x : G.Dart) :
    G.DConnect r (G.node.symm x) x :=
  Relation.ReflTransGen.refl

theorem CLink.node_symm
    (x : G.Dart) :
    G.CLink x (G.node.symm x) :=
  Or.inl rfl

theorem CLink.node
    (x : G.Dart) :
    G.CLink (G.node x) x := by
  exact Or.inl (by simp)

theorem CLink.face
    (x : G.Dart) :
    G.CLink x (G.face x) :=
  Or.inr rfl

theorem CLink.face_edge
    (x : G.Dart) :
    G.CLink x (G.face (G.edge x)) := by
  apply Or.inl
  apply G.node.injective
  simp

theorem face_edge_eq_node_symm
    (x : G.Dart) :
    G.face (G.edge x) = G.node.symm x := by
  apply G.node.injective
  simp

theorem face_edge_injective :
    Function.Injective (fun x : G.Dart => G.face (G.edge x)) := by
  intro x y hxy
  exact G.edge.injective (G.face.injective hxy)

@[simp]
theorem CPath.nil (x : G.Dart) :
    G.CPath x [] := by
  simp [CPath]

@[simp]
theorem CPath.cons (x y : G.Dart) (p : List G.Dart) :
    G.CPath x (y :: p) ↔ G.CLink x y ∧ G.CPath y p := by
  rfl

theorem list_getLastD_cons_append_of_getLast
    {α : Type _} (x y : α) (p q : List α)
    (h : (x :: p).getLastD x = y) :
    (x :: (p ++ q)).getLastD x = (y :: q).getLastD y := by
  induction p generalizing x with
  | nil =>
      simp [List.getLastD] at h ⊢
      subst y
      simp
  | cons z p ih =>
      have htail : (z :: p).getLastD z = y := by
        simpa [List.getLastD] using h
      simpa [List.getLastD] using ih z htail

theorem list_exists_first_of_exists_mem
    {α : Type _} (P : α → Prop) [DecidablePred P]
    {xs : List α}
    (hxs : ∃ x : α, x ∈ xs ∧ P x) :
    ∃ pre : List α, ∃ x : α, ∃ post : List α,
      xs = pre ++ x :: post ∧ P x ∧
        ∀ y : α, y ∈ pre → ¬ P y := by
  induction xs with
  | nil =>
      rcases hxs with ⟨x, hx, _⟩
      cases hx
  | cons x xs ih =>
      by_cases hxP : P x
      · exact ⟨[], x, xs, by simp, hxP, by simp⟩
      · have htail : ∃ y : α, y ∈ xs ∧ P y := by
          rcases hxs with ⟨y, hy, hyP⟩
          rw [List.mem_cons] at hy
          rcases hy with hy | hy
          · subst y
            exact False.elim (hxP hyP)
          · exact ⟨y, hy, hyP⟩
        rcases ih htail with ⟨pre, y, post, hsplit, hyP, hpre⟩
        refine ⟨x :: pre, y, post, ?_, hyP, ?_⟩
        · simp [hsplit]
        · intro z hz
          rw [List.mem_cons] at hz
          rcases hz with hz | hz
          · subst z
            exact hxP
          · exact hpre z hz

theorem list_exists_first_mem_of_exists_mem
    {α : Type _} [DecidableEq α]
    {c xs : List α}
    (hxs : ∃ x : α, x ∈ xs ∧ x ∈ c) :
    ∃ pre : List α, ∃ x : α, ∃ post : List α,
      xs = pre ++ x :: post ∧ x ∈ c ∧
        ∀ y : α, y ∈ pre → y ∉ c := by
  classical
  exact list_exists_first_of_exists_mem
    (fun x : α => x ∈ c) hxs

theorem list_exists_first_tail_mem_of_head_not_mem
    {α : Type _} [DecidableEq α]
    {c xs : List α} {x : α}
    (hx : x ∉ c)
    (hxs : ∃ y : α, y ∈ x :: xs ∧ y ∈ c) :
    ∃ pre : List α, ∃ y : α, ∃ post : List α,
      xs = pre ++ y :: post ∧ y ∈ c ∧
        ∀ z : α, z ∈ pre → z ∉ c := by
  classical
  rcases hxs with ⟨y, hy, hyc⟩
  have htail : ∃ y : α, y ∈ xs ∧ y ∈ c := by
    rw [List.mem_cons] at hy
    rcases hy with hy | hy
    · subst y
      exact False.elim (hx hyc)
    · exact ⟨y, hy, hyc⟩
  exact list_exists_first_mem_of_exists_mem (c := c) htail

/-- Choose the last `A`-contact before the first `B`-contact in a list that
starts in `A`, where `A` and `B` are disjoint.  The intervening list avoids
both sets.  This is the list-level content of Coq's `disjoint_subpath`
trimming step. -/
theorem list_exists_last_before_first_of_disjoint
    {α : Type _}
    {A B : Set α} {x : α} {xs : List α}
    (hxA : x ∈ A)
    (hAB : Disjoint A B)
    (hB : ∃ y : α, y ∈ x :: xs ∧ y ∈ B) :
    ∃ pre : List α, ∃ a : α, ∃ mid : List α,
      ∃ b : α, ∃ post : List α,
        x :: xs = pre ++ a :: mid ++ b :: post ∧
          a ∈ A ∧ b ∈ B ∧
            (∀ z : α, z ∈ mid → z ∉ A) ∧
              ∀ z : α, z ∈ mid → z ∉ B := by
  classical
  have hxB : x ∉ B := by
    intro hxB
    exact Set.disjoint_left.1 hAB hxA hxB
  have htailB : ∃ y : α, y ∈ xs ∧ y ∈ B := by
    rcases hB with ⟨y, hy, hyB⟩
    rw [List.mem_cons] at hy
    rcases hy with hy | hy
    · subst y
      exact False.elim (hxB hyB)
    · exact ⟨y, hy, hyB⟩
  rcases list_exists_first_of_exists_mem
      (fun y : α => y ∈ B) htailB with
    ⟨beforeB, b, post, hxs, hbB, hbeforeB⟩
  have hrevA :
      ∃ y : α, y ∈ (x :: beforeB).reverse ∧ y ∈ A :=
    ⟨x, by simp, hxA⟩
  rcases list_exists_first_of_exists_mem
      (fun y : α => y ∈ A) hrevA with
    ⟨afterARev, a, beforeARev, hrev, haA, hafterARev⟩
  let pre := beforeARev.reverse
  let mid := afterARev.reverse
  have hprefix :
      x :: beforeB = pre ++ a :: mid := by
    simpa [pre, mid, List.reverse_append] using
      congrArg List.reverse hrev
  refine ⟨pre, a, mid, b, post, ?_, haA, hbB, ?_, ?_⟩
  · calc
      x :: xs = (x :: beforeB) ++ b :: post := by simp [hxs]
      _ = pre ++ a :: mid ++ b :: post := by rw [hprefix]
  · intro z hz haZ
    exact hafterARev z (by simpa [mid] using hz) haZ
  · intro z hz hbZ
    have hzPrefix : z ∈ x :: beforeB := by
      rw [hprefix]
      simp [hz]
    rw [List.mem_cons] at hzPrefix
    rcases hzPrefix with hzPrefix | hzPrefix
    · subst z
      exact hxB hbZ
    · exact hbeforeB z hzPrefix hbZ

theorem CLink.to_reachable
    {x y : G.Dart}
    (hxy : G.CLink x y) :
    G.Reachable x y := by
  rcases hxy with hxy | hxy
  · subst y
    simpa using G.reachable_node_symm (G.node.symm x)
  · subst y
    exact G.reachable_face x

theorem cConnect_refl (x : G.Dart) :
    G.CConnect x x :=
  Relation.ReflTransGen.refl

theorem cConnect_single
    {x y : G.Dart}
    (hxy : G.CLink x y) :
    G.CConnect x y :=
  Relation.ReflTransGen.single hxy

theorem cConnect_trans
    {x y z : G.Dart}
    (hxy : G.CConnect x y)
    (hyz : G.CConnect y z) :
    G.CConnect x z :=
  Relation.ReflTransGen.trans hxy hyz

theorem cConnect_of_face_iterate
    (n : Nat) (x : G.Dart) :
    G.CConnect x (((G.face : G.Dart → G.Dart)^[n]) x) :=
  List.RelPath.reflTransGen_to_iterate (R := G.CLink) G.face
    (fun x => CLink.face (G := G) x) n x

theorem cConnect_of_nodeSymm_iterate
    (n : Nat) (x : G.Dart) :
    G.CConnect x (((G.node.symm : G.Dart → G.Dart)^[n]) x) :=
  List.RelPath.reflTransGen_to_iterate (R := G.CLink) G.node.symm
    (fun x => CLink.node_symm (G := G) x) n x

theorem cConnect_of_faceReachable
    [Fintype G.Dart]
    {x y : G.Dart}
    (hxy : PermReachable G.face x y) :
    G.CConnect x y := by
  rcases permReachable_exists_iterate G.face hxy with ⟨n, hn⟩
  simpa [hn] using G.cConnect_of_face_iterate n x

theorem cConnect_of_nodeSymmReachable
    [Fintype G.Dart]
    {x y : G.Dart}
    (hxy : PermReachable G.node.symm x y) :
    G.CConnect x y := by
  rcases permReachable_exists_iterate G.node.symm hxy with ⟨n, hn⟩
  simpa [hn] using G.cConnect_of_nodeSymm_iterate n x

theorem CLink.reverse_cConnect
    [Fintype G.Dart]
    {x y : G.Dart}
    (hxy : G.CLink x y) :
    G.CConnect y x := by
  rcases hxy with hxy | hxy
  · subst y
    apply G.cConnect_of_nodeSymmReachable
    exact PermReachable.symm G.node.symm
      (PermReachable.forward G.node.symm x)
  · subst y
    apply G.cConnect_of_faceReachable
    exact PermReachable.symm G.face
      (PermReachable.forward G.face x)

theorem CConnect.symm
    [Fintype G.Dart]
    {x y : G.Dart}
    (hxy : G.CConnect x y) :
    G.CConnect y x := by
  induction hxy with
  | refl =>
      exact G.cConnect_refl x
  | tail _ hstep ih =>
      exact Relation.ReflTransGen.trans
        (CLink.reverse_cConnect (G := G) hstep) ih

/-- A contour path that leaves a face has a first inverse-node step crossing
that face boundary.  Face steps preserve the selected face orbit, so the
first step whose endpoint is outside the orbit must be a `node.symm` step. -/
theorem CConnect.exists_nodeSymm_face_crossing
    {x y : G.Dart}
    (hxy : G.CConnect x y)
    (hnot : ¬ PermReachable G.face x y) :
    ∃ z : G.Dart,
      PermReachable G.face x z ∧
        ¬ PermReachable G.face x (G.node.symm z) := by
  induction hxy with
  | refl =>
      exact (hnot (PermReachable.refl G.face x)).elim
  | @tail b c hxb hbc ih =>
      by_cases hb : PermReachable G.face x b
      · rcases hbc with hnode | hface
        · refine ⟨b, hb, ?_⟩
          simpa [hnode] using hnot
        · have hbcFace : PermReachable G.face b c := by
            simpa [hface] using PermReachable.forward G.face b
          exact
            (hnot (PermReachable.trans G.face hb hbcFace)).elim
      · exact ih hb

theorem Link.to_cConnect
    {x y : G.Dart}
    (hxy : G.Link x y) :
    G.CConnect x y := by
  rcases hxy with hxy | hxy | hxy
  · subst y
    have hnode : G.CConnect x (G.node.symm x) :=
      Relation.ReflTransGen.single (CLink.node_symm (G := G) x)
    have hface :
        G.CConnect (G.node.symm x)
          (G.face.symm (G.node.symm x)) :=
      G.cConnect_of_faceReachable
        (PermReachable.backward G.face (G.node.symm x))
    have hedge : G.face.symm (G.node.symm x) = G.edge x :=
      G.mirror_edge_original x
    simpa [hedge] using Relation.ReflTransGen.trans hnode hface
  · subst y
    exact G.cConnect_of_nodeSymmReachable
      (PermReachable.backward G.node.symm x)
  · subst y
    exact Relation.ReflTransGen.single (CLink.face (G := G) x)

theorem Reachable.to_cConnect
    {x y : G.Dart}
    (hxy : G.Reachable x y) :
    G.CConnect x y := by
  induction hxy with
  | refl =>
      exact G.cConnect_refl x
  | tail _ hstep ih =>
      exact Relation.ReflTransGen.trans ih
        (Link.to_cConnect (G := G) hstep)

theorem Connected.cConnect
    (hG : G.Connected)
    (x y : G.Dart) :
    G.CConnect x y :=
  Reachable.to_cConnect (G := G)
    (Hypermap.Connected.reachable (G := G) hG x y)

theorem CPath.to_reachable
    {x y : G.Dart} {p : List G.Dart}
    (hp : G.CPath x (p ++ [y])) :
    G.Reachable x y := by
  induction p generalizing x with
  | nil =>
      have hxy : G.CLink x y := by
        simpa [CPath] using hp
      exact CLink.to_reachable (G := G) hxy
  | cons z p ih =>
      have hp' : G.CLink x z ∧ G.CPath z (p ++ [y]) := by
        simpa [CPath] using hp
      exact (CLink.to_reachable (G := G) hp'.1).trans (ih hp'.2)

theorem CPath.to_cConnect
    {x y : G.Dart} {p : List G.Dart}
    (hp : G.CPath x (p ++ [y])) :
    G.CConnect x y :=
  List.RelPath.to_reflTransGen hp

theorem CPath.snoc
    {x y z : G.Dart} {p : List G.Dart}
    (hp : G.CPath x p)
    (hlast : (x :: p).getLastD x = y)
    (hyz : G.CLink y z) :
    G.CPath x (p ++ [z]) :=
  List.RelPath.snoc hp hlast hyz

theorem CPath.append
    {x y : G.Dart} {p q : List G.Dart}
    (hp : G.CPath x p)
    (hlast : (x :: p).getLastD x = y)
    (hq : G.CPath y q) :
    G.CPath x (p ++ q) :=
  List.RelPath.append hp hlast hq

theorem CPath.append_cons
    {x y z : G.Dart} {p q : List G.Dart}
    (hp : G.CPath x p)
    (hlast : (x :: p).getLastD x = y)
    (hyz : G.CLink y z)
    (hq : G.CPath z q) :
    G.CPath x (p ++ z :: q) :=
  List.RelPath.append_cons hp hlast hyz hq

theorem CPath.split_append_cons
    {x y : G.Dart} {p q : List G.Dart}
    (hp : G.CPath x (p ++ y :: q)) :
    G.CPath x p ∧
      G.CLink ((x :: p).getLastD x) y ∧
        G.CPath y q :=
  List.RelPath.split_append_cons hp

theorem CPath.suffix_of_append
    {s x : G.Dart} {p q : List G.Dart}
    (hp : G.CPath s (p ++ x :: q)) :
    G.CPath x q :=
  List.RelPath.suffix_of_append hp

theorem CPath.suffix_of_append_self
    {x : G.Dart} {p q : List G.Dart}
    (hp : G.CPath x (p ++ x :: q)) :
    G.CPath x q :=
  CPath.suffix_of_append (G := G) hp

/-- A contiguous suffix of the full dart list of a contour path is again a
contour path. -/
theorem CPath.suffix_of_cons_eq_append
    {x a : G.Dart} {p pre q : List G.Dart}
    (hp : G.CPath x p)
    (hfull : x :: p = pre ++ a :: q) :
    G.CPath a q := by
  cases pre with
  | nil =>
      have hcons : x = a ∧ p = q := List.cons.inj (by simpa using hfull)
      rcases hcons with ⟨rfl, rfl⟩
      exact hp
  | cons z pre =>
      have hcons :
          x = z ∧ p = pre ++ a :: q :=
        List.cons.inj (by simpa [List.append_assoc] using hfull)
      rw [hcons.2] at hp
      exact CPath.suffix_of_append (G := G) hp

/-- Trim a nodup contour path to the segment from its last `A`-contact to its
first later `B`-contact.  The internal darts of the resulting path avoid both
disjoint sets. -/
theorem CPath.exists_trimmed_between_disjoint
    {A B : Set G.Dart} {x y : G.Dart} {p : List G.Dart}
    (hp : G.CPath x p)
    (hlast : (x :: p).getLastD x = y)
    (hnodup : (x :: p).Nodup)
    (hxA : x ∈ A)
    (hyB : y ∈ B)
    (hAB : Disjoint A B) :
    ∃ a b : G.Dart, ∃ q : List G.Dart,
      a ∈ A ∧ b ∈ B ∧
        G.CPath a (q ++ [b]) ∧
          (a :: q ++ [b]).Nodup ∧
            (∀ z : G.Dart, z ∈ q → z ∉ A ∧ z ∉ B) ∧
              ∀ z : G.Dart, z ∈ a :: q ++ [b] → z ∈ x :: p := by
  classical
  have hyMem : y ∈ x :: p := by
    rw [← hlast]
    exact List.getLastD_cons_mem x p
  rcases list_exists_last_before_first_of_disjoint
      hxA hAB ⟨y, hyMem, hyB⟩ with
    ⟨pre, a, q, b, post, hfull, haA, hbB, hqA, hqB⟩
  have hpathLong : G.CPath a (q ++ b :: post) :=
    CPath.suffix_of_cons_eq_append (G := G) hp
      (by simpa [List.append_assoc] using hfull)
  have hsplit := CPath.split_append_cons (G := G) hpathLong
  have hpath : G.CPath a (q ++ [b]) :=
    CPath.snoc (G := G) hsplit.1 rfl hsplit.2.1
  have hfullNodup :
      (pre ++ (a :: q ++ [b]) ++ post).Nodup := by
    simpa [hfull, List.append_assoc] using hnodup
  have hpathNodup : (a :: q ++ [b]).Nodup :=
    (List.nodup_append.mp
      (List.nodup_append.mp hfullNodup).1).2.1
  exact
    ⟨a, b, q, haA, hbB, hpath, hpathNodup,
      fun z hz => ⟨hqA z hz, hqB z hz⟩,
      fun z hz => by
        rw [hfull]
        simp only [List.mem_append, List.mem_cons] at hz ⊢
        tauto⟩

theorem CPath.shorten
    {x : G.Dart} {p : List G.Dart}
    (hp : G.CPath x p) :
    ∃ q : List G.Dart,
      G.CPath x q ∧
        (x :: q).getLastD x = (x :: p).getLastD x ∧
          (x :: q).Nodup ∧
            ∀ y : G.Dart, y ∈ x :: q → y ∈ x :: p := by
  classical
  let P : Nat → Prop := fun n =>
    ∀ {x : G.Dart} {p : List G.Dart},
      p.length = n →
        G.CPath x p →
          ∃ q : List G.Dart,
            G.CPath x q ∧
              (x :: q).getLastD x = (x :: p).getLastD x ∧
                (x :: q).Nodup ∧
                  ∀ y : G.Dart, y ∈ x :: q → y ∈ x :: p
  have hP : ∀ n : Nat, (∀ m : Nat, m < n → P m) → P n := by
    intro n ih x p hlen hp
    cases p with
    | nil =>
        refine ⟨[], by simp [CPath], by simp [List.getLastD], by simp, ?_⟩
        intro y hy
        exact hy
    | cons y p =>
        by_cases hxTail : x ∈ y :: p
        · rcases (List.mem_iff_append).1 hxTail with ⟨pre, post, hsplit⟩
          have hpLoop : G.CPath x (pre ++ x :: post) := by
            simpa [hsplit] using hp
          have hpostPath : G.CPath x post :=
            CPath.suffix_of_append_self (G := G) hpLoop
          have hpostLen : post.length < n := by
            have hlen' :
                (pre ++ x :: post).length = n := by
              simpa [hsplit] using hlen
            simp at hlen'
            omega
          rcases ih post.length hpostLen rfl hpostPath with
            ⟨q, hq, hlast, hnodup, hsub⟩
          refine ⟨q, hq, ?_, hnodup, ?_⟩
          · calc
              (x :: q).getLastD x = (x :: post).getLastD x := hlast
              _ = (x :: (pre ++ x :: post)).getLastD x :=
                    (List.getLastD_cons_append_self x pre post).symm
              _ = (x :: y :: p).getLastD x := by simp [hsplit]
          · intro z hz
            have hzPost : z ∈ x :: post := hsub z hz
            rw [List.mem_cons] at hzPost ⊢
            rcases hzPost with hzPost | hzPost
            · exact Or.inl hzPost
            · exact Or.inr (by
                rw [hsplit]
                exact List.mem_append_right pre
                  (List.mem_cons_of_mem x hzPost))
        · have hp' : G.CLink x y ∧ G.CPath y p := by
            simpa [CPath] using hp
          have hlt : p.length < n := by
            simp at hlen
            omega
          rcases ih p.length hlt rfl hp'.2 with
            ⟨q, hq, hlast, hnodup, hsub⟩
          refine ⟨y :: q, ⟨hp'.1, hq⟩, ?_, ?_, ?_⟩
          · simpa [List.getLastD] using hlast
          · refine List.nodup_cons.mpr ⟨?_, hnodup⟩
            intro hxq
            exact hxTail (hsub x hxq)
          · intro z hz
            rw [List.mem_cons] at hz ⊢
            rcases hz with hz | hz
            · exact Or.inl hz
            · exact Or.inr (hsub z hz)
  exact (Nat.strong_induction_on (p := P) p.length hP) rfl hp

theorem CConnect.exists_cPath
    {x y : G.Dart}
    (hxy : G.CConnect x y) :
    ∃ p : List G.Dart, G.CPath x p ∧ (x :: p).getLastD x = y := by
  induction hxy with
  | refl =>
      exact ⟨[], by simp, by simp [List.getLastD]⟩
  | tail _ hstep ih =>
      rcases ih with ⟨p, hp, hlast⟩
      exact ⟨p ++ [_],
        CPath.snoc (G := G) hp hlast hstep,
        List.getLastD_cons_append_singleton x _ p⟩

theorem CConnect.exists_short_cPath
    {x y : G.Dart}
    (hxy : G.CConnect x y) :
    ∃ p : List G.Dart,
      G.CPath x p ∧
        (x :: p).getLastD x = y ∧
          (x :: p).Nodup := by
  rcases CConnect.exists_cPath (G := G) hxy with ⟨p, hp, hlast⟩
  rcases CPath.shorten (G := G) hp with
    ⟨q, hq, hqLast, hqNodup, _⟩
  exact ⟨q, hq, by rw [hqLast, hlast], hqNodup⟩

theorem Connected.exists_cPath
    (hG : G.Connected)
    (x y : G.Dart) :
    ∃ p : List G.Dart, G.CPath x p ∧ (x :: p).getLastD x = y :=
  CConnect.exists_cPath (G := G)
    (Hypermap.Connected.cConnect (G := G) hG x y)

theorem connected_cPath
    (hG : G.Connected)
    (x y : G.Dart) :
    ∃ p : List G.Dart, G.CPath x p ∧ (x :: p).getLastD x = y :=
  Connected.exists_cPath (G := G) hG x y

theorem ListMemBeforeEq.left_mem
    {α : Type _} {xs : List α} {a b : α}
    (h : ListMemBeforeEq xs a b) :
    a ∈ xs := by
  rcases h with ⟨pre, rest, rfl, _⟩
  simp

theorem ListMemBeforeEq.right_mem
    {α : Type _} {xs : List α} {a b : α}
    (h : ListMemBeforeEq xs a b) :
    b ∈ xs := by
  rcases h with ⟨pre, rest, rfl, hb⟩
  exact List.mem_append_right pre hb

theorem ListMemBeforeEq.cons_self
    {α : Type _} (xs : List α) (a b : α)
    (hb : b ∈ a :: xs) :
    ListMemBeforeEq (a :: xs) a b :=
  ⟨[], xs, rfl, hb⟩

theorem ListMemBeforeEq.cons_tail
    {α : Type _} {xs : List α} {a b c : α}
    (h : ListMemBeforeEq xs a b) :
    ListMemBeforeEq (c :: xs) a b := by
  rcases h with ⟨pre, rest, hxs, hb⟩
  refine ⟨c :: pre, rest, ?_, hb⟩
  simp [hxs]

theorem ListMemBeforeEq.append_left
    {α : Type _} {xs ys : List α} {a b : α}
    (h : ListMemBeforeEq xs a b) :
    ListMemBeforeEq (xs ++ ys) a b := by
  rcases h with ⟨pre, rest, hxs, hb⟩
  refine ⟨pre, rest ++ ys, ?_, ?_⟩
  · simp [hxs, List.append_assoc]
  · exact List.mem_append_left ys hb

theorem ListMemBeforeEq.append_right
    {α : Type _} (xs : List α) {ys : List α} {a b : α}
    (h : ListMemBeforeEq ys a b) :
    ListMemBeforeEq (xs ++ ys) a b := by
  rcases h with ⟨pre, rest, hys, hb⟩
  refine ⟨xs ++ pre, rest, ?_, hb⟩
  simp [hys, List.append_assoc]

theorem ListMemBeforeEq.refl_of_mem
    {α : Type _} {xs : List α} {a : α}
    (ha : a ∈ xs) :
    ListMemBeforeEq xs a a := by
  induction xs with
  | nil =>
      cases ha
  | cons x xs ih =>
      rw [List.mem_cons] at ha
      rcases ha with hxa | ha
      · subst x
        exact ListMemBeforeEq.cons_self xs a a (by simp)
      · exact ListMemBeforeEq.cons_tail (ih ha)

theorem ListMemBeforeEq.append_cross
    {α : Type _} {xs ys : List α} {a b : α}
    (ha : a ∈ xs)
    (hb : b ∈ ys) :
    ListMemBeforeEq (xs ++ ys) a b := by
  induction xs with
  | nil =>
      cases ha
  | cons x xs ih =>
      rw [List.mem_cons] at ha
      rcases ha with hxa | ha
      · subst x
        refine ⟨[], xs ++ ys, by simp, ?_⟩
        simp [hb]
      · exact ListMemBeforeEq.cons_tail (ih ha)

theorem ListMemBeforeEq.map
    {α β : Type _} {xs : List α} {a b : α} (f : α → β)
    (h : ListMemBeforeEq xs a b) :
    ListMemBeforeEq (xs.map f) (f a) (f b) := by
  rcases h with ⟨pre, rest, hxs, hb⟩
  refine ⟨pre.map f, rest.map f, ?_, ?_⟩
  · simp [hxs]
  · simpa using (List.mem_map_of_mem (f := f) hb)

theorem ListMemBeforeEq.tail_of_cons_ne
    {α : Type _} {xs : List α} {c a b : α}
    (h : ListMemBeforeEq (c :: xs) a b)
    (ha : a ≠ c) :
    ListMemBeforeEq xs a b := by
  rcases h with ⟨pre, rest, hxs, hb⟩
  cases pre with
  | nil =>
      exact (ha (List.cons.inj hxs).1.symm).elim
  | cons d pre =>
      refine ⟨pre, rest, ?_, hb⟩
      exact (List.cons.inj hxs).2

theorem ListMemBeforeEq.of_map_injective
    {α β : Type _} {xs : List α} {a b : α} {f : α → β}
    (hf : Function.Injective f)
    (h : ListMemBeforeEq (xs.map f) (f a) (f b)) :
    ListMemBeforeEq xs a b := by
  induction xs with
  | nil =>
      have hmem := ListMemBeforeEq.left_mem h
      simp at hmem
  | cons c xs ih =>
      by_cases hac : a = c
      · subst c
        apply ListMemBeforeEq.cons_self
        have hbmap : f b ∈ (a :: xs).map f :=
          ListMemBeforeEq.right_mem h
        exact (List.mem_map_of_injective hf (a := b) (l := a :: xs)).mp hbmap
      · have htail :
            ListMemBeforeEq (xs.map f) (f a) (f b) :=
          ListMemBeforeEq.tail_of_cons_ne h
            (by
              intro hfa
              exact hac (hf hfa))
        exact ListMemBeforeEq.cons_tail (ih htail)

theorem Jordan.not_moebiusPath
    (hJ : G.Jordan) (q : List G.Dart) :
    ¬ G.MoebiusPath q :=
  hJ q

theorem MoebiusPath.of_cons
    {x : G.Dart} {p : List G.Dart}
    (hnodup : (x :: p).Nodup)
    (hpath : G.CPath x p)
    (hmem :
      ListMemBeforeEq p
        (G.node.symm ((x :: p).getLastD x)) (G.node x)) :
    G.MoebiusPath (x :: p) :=
  ⟨hnodup, hpath, hmem⟩

theorem MoebiusPath.nodup
    {q : List G.Dart}
    (hq : G.MoebiusPath q) :
    q.Nodup := by
  cases q with
  | nil =>
      cases hq
  | cons x p =>
      exact hq.1

theorem MoebiusPath.cPath
    {x : G.Dart} {p : List G.Dart}
    (hq : G.MoebiusPath (x :: p)) :
    G.CPath x p :=
  hq.2.1

theorem MoebiusPath.memBefore
    {x : G.Dart} {p : List G.Dart}
    (hq : G.MoebiusPath (x :: p)) :
    ListMemBeforeEq p
      (G.node.symm ((x :: p).getLastD x)) (G.node x) :=
  hq.2.2

theorem Jordan.not_cPath_to_cycle_with_node_contact
    (hJ : G.Jordan)
    {x z : G.Dart} {p c : List G.Dart}
    (hp : G.CPath x p)
    (hlink : G.CLink ((x :: p).getLastD x) z)
    (hc : G.CPath z c)
    (hpNodup : (x :: p).Nodup)
    (hcNodup : (z :: c).Nodup)
    (hdisj :
      ∀ y : G.Dart, y ∈ x :: p → y ∈ z :: c → False)
    (hnode : G.node x ∈ z :: c)
    (hzlast : G.node.symm ((z :: c).getLastD z) = z) :
    False := by
  have hpath : G.CPath x (p ++ z :: c) :=
    CPath.append_cons (G := G) hp rfl hlink hc
  have hnodup : (x :: (p ++ z :: c)).Nodup := by
    rw [← List.cons_append, List.nodup_append]
    exact ⟨hpNodup, hcNodup, by
      intro a ha b hb hab
      exact hdisj a ha (by simpa [hab] using hb)⟩
  have hmemCycle :
      ListMemBeforeEq (z :: c) z (G.node x) :=
    ListMemBeforeEq.cons_self c z (G.node x) hnode
  have hmemTail :
      ListMemBeforeEq (p ++ z :: c) z (G.node x) :=
    ListMemBeforeEq.append_right p hmemCycle
  have hlast :
      G.node.symm ((x :: (p ++ z :: c)).getLastD x) = z := by
    rw [List.getLastD_cons_append_cons, hzlast]
  have hmem :
      ListMemBeforeEq (p ++ z :: c)
        (G.node.symm ((x :: (p ++ z :: c)).getLastD x))
        (G.node x) := by
    rw [hlast]
    exact hmemTail
  exact hJ (x :: (p ++ z :: c))
    (MoebiusPath.of_cons (G := G) hnodup hpath hmem)

end Hypermap

end FourColor

end Schematic.Math.GraphTheory
